DISPLAY_LIMIT = 26

MIN_REVIEW_SCORE = 1
MAX_REVIEW_SCORE = 10

MAX_LENGTH_FIELD_NAME = 256
MAX_LENGTH_FIELD_SLUG = 50

MAX_NAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254
MAX_BIO_LENGHT = 256
MAX_CODE_LENGTH = 6

USER = 'user'
MODERATOR = 'moderator'
ADMIN = 'admin'
